### ISSUE TITLE
cargo run report error

### ISSUE THREAD

**Issue by skydig** [JoshuaPostel/spectrogram#2]
cargo run
   Compiling spectrogram v0.1.0 (C:\Users\alcatel\spectrogram)
error[E0432]: unresolved import `std::simd`
 --> src\transform\naive_simd.rs:5:10
  |
5 | use std::simd::{f64x8, Simd};
  |          ^^^^ could not find `simd` in `std`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `spectrogram` due to previous error

**Comment by JoshuaPostel** [comment]
Thanks for opening this issue. I will document how to run from source in the readme.  Namely, `cargo +nightly run`:

```
$ cargo run
   Compiling spectrogram v0.1.0 (/home/jp/proj/rust/spectrogram)
error[E0432]: unresolved import `std::simd`
 --> src/transform/naive_simd.rs:5:10
  |
5 | use std::simd::{f64x8, Simd};
  |          ^^^^ could not find `simd` in `std`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `spectrogram` due to previous error
$ cargo +nightly run
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/spectrogram`
```
